import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Navbar from '../components/Navbar/navbar'
import Footer from '../components/Footer/footer'
import { CartContextProvider } from '../hooks/useCart'
import { Toaster } from 'react-hot-toast'
import { headers } from 'next/headers';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Bodat Chic Second',
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon.ico?v=2'],
    apple: ['/apple-touch-icon.png?v=2'],
    shortcut: ['/apple-touch-icon.png']
  }
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): JSX.Element | undefined {
  const headersList = headers();
  const pathname = headersList.get("x-invoke-path") || "";
  const disabledNavFooter = ['/login', '/register']
  const isNotAuthPage = Boolean(!disabledNavFooter.includes(pathname))
  
  if (pathname !== null) {
    return (
    <html lang="en">
      <body className={`text-slate-700 ${poppins.className}`}>
        {/* settting toaster  agar dapat dipakai ke seluruh halaman sebagai sweet alert */}
        <Toaster
          toastOptions={{
            style: {
              background: 'rgb(51 65 85)',
              color: '#fff'
            }
          }}
        />
        {/* wrap dengan context sebagai penyedia data global */}
        {/* cart context digunakan sebagai penyedia data cart atau keranjang */}
        <CartContextProvider>
          <div className="flex flex-col min-h-screen ">
            {/* Artinya jika pathnya login atau register, maka navbar dan footer tidak akan muncul */}
            {isNotAuthPage  && <Navbar />}
            <main className="flex-grow bg-white font">{children}</main>
            {isNotAuthPage && <Footer />}
          </div>
        </CartContextProvider>
      </body>
    </html>
    )
  }
}
